LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := mtkril.cpp
LOCAL_SHARED_LIBRARIES := libbinder
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE := libshim_mtkril
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)
